#!/bin/bash

root_dir=`pwd`

sub_dirs=`ls -F $root_dir | grep /`

for sub_dir in $sub_dirs
do
    echo "=========$sub_dir========="
    cd $root_dir/$sub_dir
    if [ -d .git ] 
    then
        echo "git ${@:1}"
        git ${@:1}
    else
        echo "Not a git repo"
    fi
done
